//USER REGISTRATION
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

//USER LOGIN
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

//Patient Register
export const PATIENT_REGISTER_REQUEST = 'PATIENT_REGISTER_REQUEST';
export const PATIENT_REGISTER_SUCCESS = 'PATIENT_REGISTER_SUCCESS';
export const PATIENT_REGISTER_FAIL = 'PATIENT_REGISTER_FAIL';

//Patient list
export const FETCH_PATIENT_REQUEST = 'FETCH_PATIENT_REQUEST';
export const FETCH_PATIENT_SUCCESS = 'FETCH_PATIENT_SUCCESS';
export const FETCH_PATIENT_FAIL = 'FETCH_PATIENT_FAIL';

//Patient Details
export const PATIENT_DETAILS_REQUEST = 'PATIENT_DETAILS_REQUEST';
export const PATIENT_DETAILS_SUCCESS = 'PATIENT_DETAILS_SUCCESS';
export const PATIENT_DETAILS_FAIL = 'PATIENT_DETAILS_FAIL';

//firebase actions
export const FIREBASE_UPDATE_REQUEST = 'FIREBASE_UPDATE_REQUEST';
export const FIREBASE_UPDATE_SUCCESS = 'FIREBASE_UPDATE_SUCCESS';
export const FIREBASE_UPDATE_FAIL = 'FIREBASE_UPDATE_FAIL';

//Initiate Machine
export const INITIATE_MACHINE_REQUEST = 'INITIATE_MACHINE_REQUEST';
export const INITIATE_MACHINE_SUCCESS = 'INITIATE_MACHINE_SUCCESS';
export const INITIATE_MACHINE_FAIL = 'INITIATE_MACHINE_FAIL';

//Load Machine List
export const LOAD_MACHINE_LIST_REQUEST = 'LOAD_MACHINE_LIST_REQUEST';
export const LOAD_MACHINE_LIST_SUCCESS = 'LOAD_MACHINE_LIST_SUCCESS';
export const LOAD_MACHINE_LIST_FAIL = 'LOAD_MACHINE_LIST_FAIL';